[project]
name = "ecephys"
version = "0.0.6"
authors = [
  { name="Graham Findlay", email="gfindlay@wisc.edu" }
]
description = "Python tools for extracellular electrophysiology"
readme = "README.md"
requires-python = ">=3.9,<4.0"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: OS Independent"
]

dependencies = [
    "bg-atlasapi",
    "chardet",
    "colorcet",
    "dask[complete]", # 2024.2.1 was the last dask relase supporting pandas < 2, but cannot be used with Python >= 3.11.9
    "dask-image",
    "deepdiff",
    "docopt",
    "elephant",
    "ephyviewer",
    "horology",
    "ibl-neuropixel",
    "ipykernel",
    "ipympl",
    "ipython",
    "ipywidgets",
    "kcsd @ git+https://github.com/CSC-UW/kCSD-python.git", # Until upstream/PyPI use scipy.integrate.simpson.
    "mat73",
    "matplotlib >= 3.7",
    "numpy",
    "pandas", # 1.5.3 was the last pandas release before 2.0.0.
    "pyEDFlib",
    "pyfftw",
    "PyYAML",
    "ripple-detection",
    "scikit-learn",
    "scipy",
    "seaborn",
    "sortednp",
    "spikeinterface",
    "ssqueezepy @ git+https://github.com/OverLordGoldDragon/ssqueezepy.git", # Until 0.6.6 is on PyPI
    "Statsmodels",
    "tdt",
    "xarray[complete]",
    "yasa",
]

[project.optional-dependencies]
run-sorting = [
    "spikeinterface"
]
load-sorting = [
    "spikeinterface"
]

[dependency-groups]
dev = [
    "ruff"
]

[build-system]
requires = ["setuptools>=62.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.setuptools]
packages = ["ecephys"]

[tool.uv.sources]
spikeinterface = [
  { git = "https://github.com/CSC-UW/spikeinterface.git", branch = "wisc/sorting", extra = "run-sorting" },
  { git = "https://github.com/CSC-UW/spikeinterface.git", branch = "wisc/dev", extra = "load-sorting" },
]