[project]
name = "ecephys"
version = "0.0.6"
authors = [
  { name="Graham Findlay", email="gfindlay@wisc.edu" }
]
description = "Python tools for extracellular electrophysiology"
readme = "README.md"
requires-python = ">=3.9,<4.0"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: OS Independent"
]

dependencies = [
    "brainglobe-atlasapi",
    "colorcet",
    "dask[complete]", 
    # This offers the TraceImageViewer needed for displaying CSDs, plus a few bugfixes from Tom:
    "ephyviewer @ git+https://github.com/CSC-UW/ephyviewer.git", 
    # You can try to get away with the upstream, but TraceImageViewer is still not merged:
    # "ephyviewer @ git+https://github.com/NeuralEnsemble/ephyviewer.git", 
    "ibl-neuropixel",
    "ipykernel",
    "ipympl",
    "ipython",
    "ipywidgets",
    "kcsd @ git+https://github.com/CSC-UW/kCSD-python.git", # Until upstream/PyPI use scipy.integrate.simpson.
    "mat73",
    "matplotlib >= 3.7",
    "numpy",
    "pandas", 
    "pyEDFlib",
    "pyfftw",
    "PySide6", # For ephyviewer
    "PyYAML",
    "ripple-detection",
    "scikit-learn",
    "scipy",
    "seaborn",
    "sortednp",
    "spikeinterface",
    "ssqueezepy",
    "Statsmodels",
    "tdt",
    "xarray[complete]",
]

[project.optional-dependencies]
deprecated = [
    "elephant", # Used by MUA spindle detection
] # Needed to run code in ecephys.deprecated

[dependency-groups]
dev = [
    "ruff"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true